name: Build Documentation

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Install dependencies
        run: |
          pip install ./townbuilder[docs]

      - name: Build HTML docs
        run: sphinx-build -b html docs/source docs/build/html

      - name: Build LaTeX docs
        run: sphinx-build -b latex docs/source docs/build/latex

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: townbuilder.tex
          working_directory: docs/build/latex

      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v7
        with:
          name: html-docs
          path: docs/build/html/

      - name: Upload HTML static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/build/html/

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v7
        with:
          name: pdf-docs
          path: docs/build/latex/*.pdf


  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



